### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by XJX-187** [andrewsonga/Total-Recon#10]
Dear author:
When I run the command "bash preprocess/process_rawdata_stereo'maskcamliven_uniactor. sh $prefix $ishuman $gpu" for "Uni actor sequences:", it repeats [STEP2] with a prompt "IndexError: list index out of range" each time.
At the end of the final run, the folder contents in"/Total Recon/database/DAVIS/Dense/Full Solutions/cat2-stereo000-..." are empty.
![图片](https://github.com/user-attachments/assets/056e015e-9aa0-4287-830a-d694fc6e7012)
Looking forward to your reply, thank you

**Comment by XJX-187** [comment]
After running it again, there is a '. pfm' file in the folder. 
But a new problem occurred, when running "bash pre-processing/format_decesseddata_stereo'uniactor. sh $prefix $gpu", an error was reported: "AssertionError: datasets should not be an empty iterable"and the "Cameras" file was not generated in the DAVIS path.
![图片](https://github.com/user-attachments/assets/6bf17fbd-9609-445f-9526-8d12dafbd143)

**Comment by XJX-187** [comment]
Perhaps due to computer issues. It can run normally after replacing with another computer.

**Comment by Xiaoyuan-Isaac-Wang** [comment]
Hi, could you share how you solved this problem? I'm constantly facing this issue on different servers...

**Comment by XJX-187** [comment]
Try deleting the `database` folder and then re execute steps (3) - (4) of `Data`

**Comment by luminousking** [comment]
> Try deleting the `database` folder and then re execute steps (3) - (4) of `Data`
Oh, but deleting the `database` folder means deleting everything right? Then what about steps (1) - (2)? Thanks!

**Comment by Xiaoyuan-Isaac-Wang** [comment]
> Try deleting the `database` folder and then re execute steps (3) - (4) of `Data`

Oh, but deleting the database folder means deleting everything right? Then what about steps (1) - (2)? Thanks!
