### ISSUE TITLE
Issues Using "normrefcam2secondcam.npy" Transform

### ISSUE THREAD

**Issue by coltonstearns** [andrewsonga/Total-Recon#8]
Hello,

I'm trying to use the "normrefcam2secondcam.npy" transformation to transform every "left camera" pose into the reference frame of the "right camera" poses. If normrefcam2secondcam is the affine transformation from left-camera world coordinates to right-camera world coordinates, I tried (what I believe should have worked): NEW_POSE = affine(LEFT_POSE) @ inverse(normrefcam2secondcam). However, the resulting poses seem to be misaligned off slightly. Basically, how did you use the normrefcam2secondcam transformation? Any clarification on changes of camera coordinate systems would be greatly appreciated.
Thanks in advance!

**Comment by coltonstearns** [comment]
Ah wait, I may have figured it out - is it that normrefcam2secondcam maps from the left **camera coordinates** to right camera coordinates (i.e. not world coords)?

**Comment by andrewsonga** [comment]
Yes, `normrefcam2secondcam` maps from the left camera (the reference view) to the right camera coordinates (the "second" camera).

**Comment by andrewsonga** [comment]
@coltonstearns Were you able to resolve this issue when using `normrefcam2secondcam.npy`?
Please let me know if you need additional assistance :)

**Comment by coltonstearns** [comment]
Yes resolved it, and closing the issue now. Sorry for my delay!
